experiment:
    name: spring_surrogate_v1
    seed: 42

data:
    t_start: 0.0
    t_end: 10.0
    num_points: 1000
    n_samples: 500
    m_range: [0.5, 2.0]
    c_range: [0.1, 1.0]
    k_range: [1.0, 5.0]

model:
    hidden_sizes: [64, 128]
    lr: 0.001
    epochs: 300
    batch_size: 64

artifacts:
    output_dir: model_registry/v1
    model_filename: model.pt

mlflow:
    enabled: true
    tracking_uri: "file:./mlruns"